filetype plugin indent on
syntax on

set number
set relativenumber

set incsearch
set hlsearch

set linebreak
set breakindent

let g:nord_cursor_line_number_background = 1
let g:nord_uniform_diff_background = 1
let g:nord_underline = 1
colorscheme nord
