filetype plugin indent on
syntax on

set number
set relativenumber

set hlsearch
set incsearch

set cursorline

set laststatus=2
set noshowmode

set breakindent
set linebreak

let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }
let g:nord_cursor_line_number_background = 1
let g:nord_uniform_diff_background = 1
let g:nord_italic = 1
let g:nord_italic_comments = 1
let g:nord_underline = 1
colorscheme nord

let g:mapleader = ' '
nnoremap <CR> :nohlsearch<CR>

nnoremap <Leader>y :%y+<CR>

nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
